### ISSUE TITLE
#US011 Etiquetas

### ISSUE THREAD

**Issue by Gabrieltornier** [PNovillo/proyectointegradorfullstack#142]
Crear al menos una etiqueta por cada tecnología nombrada.
● Luego en experiencia laboral debe de etiquetar cada entrada con al menos una
de las etiquetas creadas.
● Por ejemplo, si tiene una entrada titulada “Proyecto académico con Python”,
deberá etiquetarlo con “Python”.

**Comment by candelaiaraneil** [comment]
- etiquetas creadas
- proyectos en la pestaña "experiencia laboral" etiquetados correctamente
