### ISSUE TITLE
#US07 Registro de pacientes

### ISSUE THREAD

**Issue by PNovillo** [PNovillo/proyectointegradorfullstack#23]
Como usuario registrado, quiero poder guardar información de mis pacientes en una base de datos, para poder gestionar sus turnos o recibir información de consultas referidas a ellos.

**Comment by MelGaray04** [comment]
Se completo el formulario de paciente con las siguientes especificaciones: Sección con datos personales (nombre completo, DNI, edad, etc) que también incluye los datos para poder contactar al paciente (teléfono y e-mail) y sección con el domicilio (dirección, localidad, etc). Toda esta información por el momento se envía vía e-mail y desde dicho e-mail se puede consultar el registro de pacientes, en un futuro próximo se podrá enlazar este formulario con la base de datos correspondiente.
