### ISSUE TITLE
#US08 SmartLab - Formulario de carga de turno.

### ISSUE THREAD

**Issue by PNovillo** [PNovillo/proyectointegradorfullstack#31]
Como usuario registrado, quiero poder obtener el turno e información del mismo de manera digital. (Podría ser mediante el envió de un mail con la información).
Se llena formulario con la información que corresponda, el botón envía esa info a una casilla de email, y de esa manera simulamos la expedición de turnos, esto de manera INICIAL para testear funcionamiento, hasta poder vincularlo con la base de datos y el host.

**Comment by JoseZaragoza7** [comment]
Se subió el archivo html que muestra el formulario de solicitud y elección de turno con la especialidad que se necesite
